### ISSUE TITLE
[Question] Design choice for using regexp

### ISSUE THREAD

**Issue by pierreTklein** [UCSDTESC/Check-in#119]
Hey! Dev-lead from [HackMcgill](https://github.com/hackmcgill/) here. I was having a look at your code-base, and I'm really impressed!

I'm curious as to why you chose to use regexp to check for email and username for passport-- is there a reason beyond making it case-insensitive?

https://github.com/UCSDTESC/Check-in/blob/671b6d8636bcba5e7a15d98cb195c9b59081310d/src/server/config/passport.js#L35

**Comment by RedbackThomson** [comment]
The only reason is to remove case-sensitivity from the login form. We don't require the endpoint to receive a lowercase username, so we need to do it in the query.
The reason we don't convert all usernames to lowercase before inserting into the DB is so that certain companies can have case-specific usernames (for example GitHub rather than just github).
